version: '3'
services:
  backend:
    build: ./backend/
    ports:
     - "3030:3030"
    depends_on: 
      - db
  db:
    build: ./db/
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_USER=infra
     - POSTGRES_PASSWORD=1234
